name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run gen

    - name: Deploy Project
      run: |
        git config --global user.name "github-actions-bot"
        git config --global user.email "support+actions@github.com"
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"

