name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run gen

    - name: Setup SSH for Deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Configure SSH for GitHub
      run: |
        SSH_REPO="git@github.com:${GITHUB_REPOSITORY}.git"
        git remote set-url origin $SSH_REPO

    - name: Deploy Project with gh-pages
      run: |
        git config --global user.name "github-actions-bot"
        git config --global user.email "support+actions@github.com"
        npm run deploy
