name: Main

on:
  push:
    branches:
      - main

permissions:  # Setting permissions globally for all jobs
  contents: write
  deployments: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run gen

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}
